package feed

import (
	"context"

	"connectrpc.com/connect"
	"google.golang.org/protobuf/types/known/timestamppb"

	feedv1 "github.com/ventura-app/ventura/gen/go/ventura/feed/v1"
	placesv1 "github.com/ventura-app/ventura/gen/go/ventura/places/v1"
	userv1 "github.com/ventura-app/ventura/gen/go/ventura/user/v1"
)

// Handler implements the FeedServiceHandler interface generated by ConnectRPC.
type Handler struct{}

func NewHandler() *Handler {
	return &Handler{}
}

func (h *Handler) GetFeed(
	ctx context.Context,
	req *connect.Request[feedv1.GetFeedRequest],
) (*connect.Response[feedv1.GetFeedResponse], error) {

	// One hardcoded post — no DB, no auth, just the contract flowing over the wire.
	post := &feedv1.Post{
		Id:           "post-001",
		VideoUrl:     "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8", // public HLS test stream
		ThumbnailUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg",
		Author: &userv1.User{
			Id:        "user-001",
			Email:     "traveler@ventura.app",
			FirstName: "Esteban",
			LastName:  "Traveler",
		},
		Place: &placesv1.Place{
			Id:          "place-001",
			Name:        "Guatemala City",
			Description: "The capital of Guatemala",
			Location: &placesv1.LatLng{
				Latitude:  14.6349,
				Longitude: -90.5069,
			},
			OwnerId: "user-001",
		},
		ViewCount: 1000,
		LikeCount: 42,
		CreatedAt: timestamppb.Now(),
	}

	return connect.NewResponse(&feedv1.GetFeedResponse{
		Posts:         []*feedv1.Post{post},
		NextPageToken: "",
	}), nil
}